import { test } from 'node:test';
import assert from 'node:assert/strict';
import worker from './index.js';
class KV { data=new Map(); async get(k,type){const v=this.data.get(k)?.value;if(v===undefined)return null;return type==='json'?JSON.parse(v):v;} async put(k,value,options={}){this.data.set(k,{value,metadata:options.metadata});} async getWithMetadata(k){return this.data.get(k)||{value:null};} async list({prefix}){return {keys:[...this.data].filter(([k])=>k.startsWith(prefix)).map(([name,v])=>({name,metadata:v.metadata})),list_complete:true};} }
const origin='https://example.com';
const req=(path,method='GET',body,cookie)=>new Request(origin+path,{method,headers:{Origin:origin,...(body?{'Content-Type':'application/json'}:{}),...(cookie?{Cookie:cookie}:{})},body:body?JSON.stringify(body):undefined});
const env=()=>({SITE_CONTENT:new KV(),ADMIN_PASSWORD:'test-strong-password',ASSETS:{fetch:()=>new Response('static')}});
async function login(e){const r=await worker.fetch(req('/api/login','POST',{password:e.ADMIN_PASSWORD}),e);assert.equal(r.status,200);return r.headers.get('Set-Cookie').split(';')[0];}
test('admin authentication rejects unauthenticated writes, wrong passwords, cross-origin writes and tampered cookies',async()=>{const e=env();assert.equal((await worker.fetch(req('/api/content','PUT',{}),e)).status,401);assert.equal((await worker.fetch(req('/api/login','POST',{password:'bad'}),e)).status,401);const c=await login(e);assert.equal((await worker.fetch(req('/api/session','GET',undefined,c+'bad'),e)).status,401);const r=new Request(origin+'/api/content',{method:'PUT',headers:{Origin:'https://evil.example',Cookie:c},body:'{}'});assert.equal((await worker.fetch(r,e)).status,403);});
test('content persistence, safe URL validation and image signature validation',async()=>{const e=env(),c=await login(e);const content={texts:{'Settings.logo':'/logo.png'},settings:{phone:'123',email:'test@example.com',whatsapp:'123'},services:[],collectionItems:[],processSteps:[],extraSections:[]};assert.equal((await worker.fetch(req('/api/content','PUT',content,c),e)).status,200);assert.deepEqual(await (await worker.fetch(req('/api/content'),e)).json(),content);content.texts['Settings.logo']='javascript:alert(1)';assert.equal((await worker.fetch(req('/api/content','PUT',content,c),e)).status,400);const f=new FormData();f.set('file',new File(['<svg>bad</svg>'],'bad.png',{type:'image/png'}));assert.equal((await worker.fetch(new Request(origin+'/api/upload',{method:'POST',headers:{Origin:origin,Cookie:c},body:f}),e)).status,400);const g=new FormData();g.set('file',new File([new Uint8Array([71,73,70,56,57,97])],'good.gif',{type:'image/gif'}));const r=await worker.fetch(new Request(origin+'/api/upload',{method:'POST',headers:{Origin:origin,Cookie:c},body:g}),e);assert.equal(r.status,200);const u=(await r.json()).url;assert.equal((await worker.fetch(req(u),e)).headers.get('Content-Type'),'image/gif');});
test('enquiries are saved, inbox requires login, and missing setup is explicit',async()=>{const e=env();const content={name:'Client',email:'client@example.com',phone:'123',address:'Sydney',items:'Laptops'};assert.equal((await worker.fetch(req('/api/enquiries','POST',content),e)).status,200);assert.equal((await worker.fetch(req('/api/enquiries'),e)).status,401);const c=await login(e);assert.equal((await (await worker.fetch(req('/api/enquiries','GET',undefined,c),e)).json()).items.length,1);assert.equal((await worker.fetch(req('/api/content'),{})).status,503);});
